<script setup lang="ts">
import { reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import type { GenreMetric, GenreMetricPayload } from '../../types/genreMetric'
import type { GenreModule } from '../../types/genreModule'
const open=defineModel<boolean>({required:true})
const props=defineProps<{metric:GenreMetric|null;modules:GenreModule[];saving?:boolean}>()
const emit=defineEmits<{save:[payload:GenreMetricPayload]}>()
const form=reactive<GenreMetricPayload>({genre_module_id:'',platform:'',channel:'',period:'',average_age:28,age_group:'middle',education_level:'medium',audience_share:0,heat_index:0,trend:'stable',is_core:false,sample_size:0,data_source:'',remark:''})
const errors=ref<Record<string,string>>({})
function defaults(){return{genre_module_id:props.modules[0]?.id||'',platform:'综合平台',channel:'全频道',period:new Date().toISOString().slice(0,7),average_age:28,age_group:'middle' as const,education_level:'medium' as const,audience_share:10,heat_index:50,trend:'stable' as const,is_core:false,sample_size:0,data_source:'',remark:''}}
watch([open,()=>props.metric],()=>{errors.value={};if(!open.value)return;Object.assign(form,props.metric?{genre_module_id:props.metric.genre_module_id,platform:props.metric.platform,channel:props.metric.channel,period:props.metric.period,average_age:props.metric.average_age,age_group:props.metric.age_group,education_level:props.metric.education_level,audience_share:props.metric.audience_share,heat_index:props.metric.heat_index,trend:props.metric.trend,is_core:props.metric.is_core,sample_size:props.metric.sample_size,data_source:props.metric.data_source,remark:props.metric.remark}:defaults())},{immediate:true})
function validate(){const next:Record<string,string>={};if(!form.genre_module_id)next.genre_module_id='请选择题材';if(!form.platform.trim())next.platform='请输入数据平台';if(!form.channel.trim())next.channel='请输入频道';if(!/^\d{4}-(0[1-9]|1[0-2]|Q[1-4])$/.test(form.period))next.period='使用 YYYY-MM 或 YYYY-Q1 格式';if(!(form.average_age>0&&form.average_age<=100))next.average_age='平均年龄须大于 0 且不超过 100';if(!(form.audience_share>=0&&form.audience_share<=100))next.audience_share='用户占比须在 0—100';if(!(form.heat_index>=0&&form.heat_index<=100))next.heat_index='热度须在 0—100';if(form.sample_size<0)next.sample_size='样本量不能小于 0';errors.value=next;return!Object.keys(next).length}
function submit(){if(!validate())return ElMessage.warning('请检查表单中的错误');emit('save',{...form,platform:form.platform.trim(),channel:form.channel.trim(),period:form.period.trim(),data_source:form.data_source.trim(),remark:form.remark.trim()})}
</script>

<template>
  <el-drawer v-model="open" :title="metric?'编辑定位数据':'新增定位数据'" size="620px"><div class="editor-body"><div class="form-intro"><b>年龄—学历定位记录</b><span>保存后气泡位置、大小、区域占比与均值线会立即刷新。</span></div><el-form label-position="top"><div class="form-grid"><el-form-item label="题材" required :error="errors.genre_module_id"><el-select v-model="form.genre_module_id" filterable class="full"><el-option v-for="item in modules" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="数据周期" required :error="errors.period"><el-input v-model="form.period" placeholder="2026-08 或 2026-Q3"/></el-form-item><el-form-item label="数据平台" required :error="errors.platform"><el-input v-model="form.platform"/></el-form-item><el-form-item label="频道" required :error="errors.channel"><el-input v-model="form.channel"/></el-form-item><el-form-item label="平均年龄" required :error="errors.average_age"><el-input-number v-model="form.average_age" :min="0.1" :max="100" :step="0.1" class="full"/></el-form-item><el-form-item label="年龄层级" required><el-select v-model="form.age_group" class="full"><el-option label="少年（12—22）" value="youth"/><el-option label="中年（23—50）" value="middle"/><el-option label="老年（51+）" value="senior"/></el-select></el-form-item><el-form-item label="学历层级" required><el-select v-model="form.education_level" class="full"><el-option label="低学历" value="low"/><el-option label="中学历" value="medium"/><el-option label="高学历" value="high"/></el-select></el-form-item><el-form-item label="用户占比（%）" required :error="errors.audience_share"><el-input-number v-model="form.audience_share" :min="0" :max="100" :step="0.1" class="full"/></el-form-item><el-form-item label="热度指数" required :error="errors.heat_index"><el-input-number v-model="form.heat_index" :min="0" :max="100" :step="0.1" class="full"/></el-form-item><el-form-item label="趋势" required><el-select v-model="form.trend" class="full"><el-option label="上升" value="rising"/><el-option label="稳定" value="stable"/><el-option label="下降" value="falling"/></el-select></el-form-item><el-form-item label="样本量" :error="errors.sample_size"><el-input-number v-model="form.sample_size" :min="0" class="full"/></el-form-item><el-form-item label="重点题材"><el-switch v-model="form.is_core" inline-prompt active-text="是" inactive-text="否"/></el-form-item><el-form-item label="数据来源" class="wide"><el-input v-model="form.data_source" maxlength="200"/></el-form-item><el-form-item label="备注" class="wide"><el-input v-model="form.remark" type="textarea" :rows="4" maxlength="1000" show-word-limit/></el-form-item></div></el-form></div><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" :loading="saving" @click="submit">保存并刷新图表</el-button></template></el-drawer>
</template>

<style scoped>
.editor-body{padding:20px 24px 35px}.form-intro{display:grid;gap:4px;margin-bottom:18px;padding:12px;border-left:2px solid var(--accent);background:var(--accent-soft)}.form-intro b{font-size:10px}.form-intro span{color:var(--text-muted);font-size:8px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 12px}.form-grid .wide{grid-column:1/-1}.full{width:100%}
</style>
